name: docs-ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependecies
        run: pip install -r requirements.txt
        working-directory: docs
      - name: Deploy docs on 'gh-pages' branch
        run: mkdocs gh-deploy --force
